import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';
import { copyFileSync, mkdirSync, readFileSync } from 'fs';
import { existsSync } from 'fs';

const banner = `/*
${readFileSync('LICENSE', 'utf8')}

${readFileSync('NOTICE', 'utf8')}

${readFileSync('THIRD-PARTY-NOTICES', 'utf8')}

THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/suite/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2020',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'dist/main.js',
});

if (prod) {
	await context.rebuild();

	// Ensure dist directory exists
	if (!existsSync('dist')) {
		mkdirSync('dist', { recursive: true });
	}

	// Copy required distribution files to dist/
	copyFileSync('manifest.json', 'dist/manifest.json');
	copyFileSync('styles.css', 'dist/styles.css');
	copyFileSync('LICENSE', 'dist/LICENSE');
	copyFileSync('NOTICE', 'dist/NOTICE');
	copyFileSync('THIRD-PARTY-NOTICES', 'dist/THIRD-PARTY-NOTICES');
	copyFileSync('STATUS-LISTS.md', 'dist/STATUS-LISTS.md');
	copyFileSync('README.md', 'dist/README.md');

	process.exit(0);
} else {
	await context.watch();
}
